name: Build and publish packages

on:
  push:
    branches:
      - main
      - develop

jobs:
  job1:
    name: Build and publish FeatureFlag.Management
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Fetch all repository
      run: git fetch --unshallow
      
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Change version on csproj file
      run: sed -i -e 's/Version>[0-9a-z.-]*</Version>'$GITVERSION_NUGETVERSION'</' ./FeatureFlag.Management/FeatureFlag.Management.csproj
      
    - name: Build
      run: dotnet build ./FeatureFlag.Management/FeatureFlag.Management.csproj --configuration Release

    - name: Pack
      run: dotnet pack ./FeatureFlag.Management/FeatureFlag.Management.csproj  --output ./artifacts --configuration Release

    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      if: github.ref == 'refs/heads/develop'
      with:
        nupkg-path:  './artifacts/*.nupkg'
        repo-owner:  'felipebaltazar'
        gh-user:  'felipebaltazar'
        token:  ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: ./FeatureFlag.Management/FeatureFlag.Management.csproj
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
  job2:
    name: Build and publish FeatureFlag.Management.Firebase
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Fetch all repository
      run: git fetch --unshallow
      
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Change version on csproj file
      run: sed -i -e 's/Version>[0-9a-z.-]*</Version>'$GITVERSION_NUGETVERSION'</' ./FeatureFlag.Management.Firebase/FeatureFlag.Management.Firebase.csproj

    - name: Build
      run: dotnet build ./FeatureFlag.Management.Firebase/FeatureFlag.Management.Firebase.csproj --configuration Release

    - name: Pack
      run: dotnet pack ./FeatureFlag.Management.Firebase/FeatureFlag.Management.Firebase.csproj  --output ./artifacts --configuration Release

    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      if: github.ref == 'refs/heads/develop'
      with:
        nupkg-path:  './artifacts/*.nupkg'
        repo-owner:  'felipebaltazar'
        gh-user:  'felipebaltazar'
        token:  ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish NuGet.org
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: ./FeatureFlag.Management.Firebase/FeatureFlag.Management.Firebase.csproj
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

  job3:
    name: Build and publish FeatureFlag.Management.Xamarin.Forms
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Fetch all repository
      run: git fetch --unshallow
      
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Change version on csproj file
      run: sed -i -e 's/Version>[0-9a-z.-]*</Version>'$GITVERSION_NUGETVERSION'</' ./FeatureFlag.Management.Xamarin.Forms/FeatureFlag.Management.Xamarin.Forms.csproj
      
    - name: Build
      run: dotnet build ./FeatureFlag.Management.Xamarin.Forms/FeatureFlag.Management.Xamarin.Forms.csproj --configuration Release

    - name: Pack
      run: dotnet pack ./FeatureFlag.Management.Xamarin.Forms/FeatureFlag.Management.Xamarin.Forms.csproj  --output ./artifacts --configuration Release

    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      if: github.ref == 'refs/heads/develop'
      with:
        nupkg-path:  './artifacts/*.nupkg'
        repo-owner:  'felipebaltazar'
        gh-user:  'felipebaltazar'
        token:  ${{ secrets.GITHUB_TOKEN }}
      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: ./FeatureFlag.Management.Xamarin.Forms/FeatureFlag.Management.Xamarin.Forms.csproj
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
